# 基本配置
server:
  port: 80
spring:
  data:
    mongodb:
      host: localhost     # mongo 地址
      port: 27017         # mongo 端口号
      database: local
#      authentication-database: admin   # 验证数据库
 #     username: admin                  # 用户名
 #     password: admin                  # 密码
#anyhaa anymk  anymn  anyiii  anynm  anyyyy
  thymeleaf:
    cache: false
    cache-period: 0
  template:
    cache: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%15.15t] %-40.40c{1.} [%X{user}] : %m%n%xwEx"

# 简书配置
jianshu:
  user-id: 7b7ec6f2db21